### ISSUE TITLE
Unresolved reference with 1.0.0-alpha03 in Kotlin 1.4

### ISSUE THREAD

**Issue by SteinerOkay** [ReactiveCircus/FlowBinding#104]
After update to 1.0.0-alpha03 and Kotlin 1.4 I received red error in imports of extensions functions like beforeTextChanges and etc and of course this function unavailable in code.

I think it related with explicit API mode.

**Comment by ychescale9** [comment]
Thanks for reporting. This is a packaging options issue where "META-INF/*.kotlin_module" was excluded to avoid compiler warnings but apparently no longer works with Kotlin 1.4.

Will fix and push a new release soon.

**Comment by ychescale9** [comment]
`1.0.0-alpha04` is now available.
