### ISSUE TITLE
Expose common dependencies (like safeOffer) as public apis

### ISSUE THREAD

**Issue by jakoss** [ReactiveCircus/FlowBinding#108]
I'm using this library for all standard views, but every now and again i have to use external library that don't have support of FlowBinding. I'd love to add a new extension for it using the same method used by all FlowBinding methods. It would be pretty straightforward, but functions like safeOffer are restricted to library group. I'm not sure if you would want to make those public, since it is technically an implementation detail, but it would make my life better :)

**Comment by ychescale9** [comment]
Sounds like a reasonable request, especially when those APIs are all [public](https://github.com/ReactiveCircus/FlowBinding/blob/main/flowbinding-common/api/flowbinding-common.api) anyway.

I'm slightly concerned that people might start using and relying on these APIs for things unrelated to FlowBinding (which is the problem the `@RestrictTo` annotation tries to solve). For example, `safeOffer` is a workaround for [this issue](https://github.com/Kotlin/kotlinx.coroutines/issues/974) which will be addressed in Coroutines 1.4 release. Keeping it an implementation detail within this library group would allow us to break API compatibility without much concern by removing this extension function once we depend on Coroutines 1.4.

I'm wondering how often do you need to implement custom FlowBindings and how annoying is it to just copy these 3 functions into your codebase?

**Comment by jakoss** [comment]
It isn't annoying and that's what i'm doing now. It's just my OCD kicking in. I always worry about being compliant with 3rd party libraries if i extend them in any way.

Maybe it would be sensible if library exposed some functions that are more generic and you could tweak them under the hood. So these functions would be more like a contract with your library. You could also force these functions to work in some scope that's specific to your library, for example you could create your own version of `callbackFlow` (like `bindingFlow`) and make these functions work in this scope?
