### ISSUE TITLE
Use `StateFlow` for flows emiting state changes instead of `InitialValueFlow`

### ISSUE THREAD

**Issue by GSala** [ReactiveCircus/FlowBinding#114]
Does it make sense to replace `InitialValueFlow` with `StateFlow` in all `Flow`s emitting changes in view state?

**Comment by ychescale9** [comment]
We considered returning `StateFlow` for widgets that emit state, but decided to go with `InitialValueFlow` to allow users to explicitly opt-out of the behavior by calling `skipInitialValue()` which is consistent with RxBinding (see https://github.com/ReactiveCircus/FlowBinding/issues/94). 

Are there any specific reasons why you think `StateFlow` is more appropriate?

**Comment by GSala** [comment]
I read through #94 . I see the main problems for using `StateFlow` were (1) "strong equality-based conflation "  and (2) "allowing consumers to access the current value imperatively".

Regarding (1) I think the api should have a clear difference between observing state (through `StateFlow`), and observing events (through `Flow`). If "strong equality-based conflation" is a problem, it means we are observing events, and not state. Because when dealing with state, we shouldn't care about a repeating event that didn't mutate the state in any way. 

Regarding (2) I haven't looked up the implementation details of the library, but would it be reasonable to delegate the call to the actual view like @BenTilbrook suggests in https://github.com/ReactiveCircus/FlowBinding/issues/94#issuecomment-639263331

**Comment by ychescale9** [comment]
Thanks for sharing your thoughts. Both of your points sound reasonable but I want to think a bit more about it.

In the mean could you share how you intend to use a binding that emits `StateFlow`? Specifically I'm curious about how it differs / improves from the current `InitialValueFlow` implementation.

Also since we're in beta now, ideally I'd like to avoid making breaking changes unless there are really compelling reasons to do so.

 @BenTilbrook @svenjacobs any thoughts?

BTW I just enabled GitHub Discussions for this project. Maybe we can [try it out](https://github.com/ReactiveCircus/FlowBinding/discussions) as this seems like an open-ended discussion?

**Comment by BenTilbrook** [comment]
`StateFlow` isn't stable for inheritance by libraries as of `1.4.2`. This may complicate my earlier suggestion of delegating the `value` call to the `View`.

**Comment by svenjacobs** [comment]
What would be the benefits of using `StateFlow`?

**Comment by GSala** [comment]
I don't think there's benefits other than just modelling view's state with a known type, instead of introducing a new external type of flow whose behavior is unknown. 
If API compatibility is an issue now, then clearly this won't be the way to go. 

Also, after a discussion on the Kotlin Slack, Adam Powell advocates it's better if Views consume state, and produce events. In that case, it won't make sense to use `StateFlow`. 

Maybe for my use case it made more sense to react to state only (including initial state, without caring about the events, and whether more events have happened without changing state) but generally it might not be the right approach.

**Comment by svenjacobs** [comment]
> instead of introducing a new external type of flow whose behavior is unknown.

I personally don't think `InitialValueFlow` is a big deal because it's just a very thin wrapper around `Flow`, implementing the `Flow` interface. Therefore it can be used just like `Flow`.
