### ISSUE TITLE
Why doesn't clicks() return the Flow<View>

### ISSUE THREAD

**Issue by Zengyonghao** [ReactiveCircus/FlowBinding#122]
I want to merge multiple click events, but Flow<Unit> prevents me from distinguishing the source of the events
` merge(binding.actionWechat.clicks(),
                binding.actionFacebook.clicks(),
                binding.actionTwitter.clicks(),
                binding.actionWhatapp.clicks())
                .onEach {   
               }`

**Comment by Zengyonghao** [comment]
like this

**Comment by Zengyonghao** [comment]
like this

**Comment by Zengyonghao** [comment]
like this
`  val listener = View.OnClickListener {
        safeOffer(it)
    }`

**Comment by ychescale9** [comment]
Does this work?
```kotlin
class ClickEvent(val view: View)

merge(
  binding.actionWechat.clicks().map { ClickEvent(binding.actionWechat) },
  binding.actionFacebook.clicks().map { ClickEvent(binding.actionFacebook) },
  binding.actionTwitter.clicks().map { ClickEvent(binding.actionTwitter) },
  binding.actionWhatapp.clicks().map { ClickEvent(binding.actionWhatapp) },
).onEach {
  // event.view
}
```

**Comment by Zengyonghao** [comment]
> Does this work?
> 
> ```kotlin
> class ClickEvent(val view: View)
> 
> merge(
>   binding.actionWechat.clicks().map { ClickEvent(binding.actionWechat) },
>   binding.actionFacebook.clicks().map { ClickEvent(binding.actionFacebook) },
>   binding.actionTwitter.clicks().map { ClickEvent(binding.actionTwitter) },
>   binding.actionWhatapp.clicks().map { ClickEvent(binding.actionWhatapp) },
> ).onEach {
>   // event.view
> }
> ```

thanks. This can solve the problem
