### ISSUE TITLE
Suggestion: support Lifecycle events

### ISSUE THREAD

**Issue by svenjacobs** [ReactiveCircus/FlowBinding#70]
Thanks for this useful library 👍 

I suggest adding a new artifact `flowbinding-lifecycle` which supports `Flow` of [Lifecycle](https://developer.android.com/jetpack/androidx/releases/lifecycle) events. Here's a proposal of how this could look like:

```kotlin
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.Lifecycle.Event
import androidx.lifecycle.LifecycleObserver
import androidx.lifecycle.LifecycleOwner
import androidx.lifecycle.OnLifecycleEvent
import kotlinx.coroutines.channels.awaitClose
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.callbackFlow
import kotlinx.coroutines.flow.filter
import kotlinx.coroutines.flow.map

fun Lifecycle.events(): Flow<Event> = callbackFlow {
    val observer = object : LifecycleObserver {
        @OnLifecycleEvent(Event.ON_ANY)
        fun onEvent(owner: LifecycleOwner, event: Event) {
            offer(event)
        }
    }
    addObserver(observer)
    awaitClose { removeObserver(observer) }
}

fun Lifecycle.onCreate(): Flow<Unit> =
    events()
        .filter { it == Event.ON_CREATE }
        .map { Unit }
```

Thank you!

**Comment by ychescale9** [comment]
Hi. Thanks for the feature request!

Can you give me a couple of use cases i.e. what would you do with a `Flow` of LifecycleEvents?

**Comment by svenjacobs** [comment]
> Can you give me a couple of use cases i.e. what would you do with a Flow of LifecycleEvents?

I'm currently implementing the Model-View-Intent pattern in an Android application utilizing coroutines and Flow. My idea is that any kind of event, be it a click event or a lifecycle event, is represented through Flows. So the only communication between the view and the "presenter" is through Flow.

```kotlin
interface SomeView {
  val onCreateEvents: Flow<Unit>
  val onButtonClickEvents: Flow<Unit>
}
```

then somewhere else

```kotlin
   val onCreateFlow = view.onCreateEvents
    .onEach { // Do something with this event }

   val onButtonClickFlow = view.onButtonClickEvents
    .onEach { // Do something with this event }

  flowOf(
    onCreateFlow,
    onButtonClickFlow
  ).flattenMerge().launchIn(someScope)
```

The example is greatly simplified but I hope you get what I mean.

**Comment by ychescale9** [comment]
> ```
>val onCreateFlow = view.onCreateEvents
>   .onEach { // Do something with this event }
>```
What would you put in the `onEach` block here? 😄Is it some kind of side-effect or mapping to some sealed `Event` type that the presenter / view model takes as input?

I'm asking as I can't quite wrap my head around how a stream of lifecycle events can help in a MVI setup. Ideally the presenter / viewmodel should not be aware of the Android Lifecycle. The only use case I can think of where monitoring Lifecycle events is useful (other than subscribing and unsubscribing event listeners) is analytics reporting. Am I missing something?

Anyway this library probably shouldn't be too opinionated on how it's used. So I'll work on this next week.

**Comment by svenjacobs** [comment]
> What would you put in the onEach block here? 😄Is it some kind of side-effect or mapping to some sealed Event type that the presenter / view model takes as input?

As I said my example is simplified ;) What I do is (instead of `onEach`) map the incoming events into changes of a `State` data class. This `State` represents the UI state. In the `onCreate` event for example I would start loading some data and put it in the state.

**Comment by ychescale9** [comment]
Got you 👍

**Comment by svenjacobs** [comment]
Nice 😄 I'm looking forward to your implementation!

**Comment by ychescale9** [comment]
Added new [LifecycleEventFlow](https://github.com/ReactiveCircus/FlowBinding/blob/master/flowbinding-lifecycle/src/main/java/reactivecircus/flowbinding/lifecycle/LifecycleEventFlow.kt). This will be in the next release.

**Comment by svenjacobs** [comment]
Nice, thanks! 👍

**Comment by ychescale9** [comment]
`0.9.0` is out. Should be available on Maven Central soon.
