### ISSUE TITLE
Suggestion: Support back button presses through OnBackPressedDispatcher

### ISSUE THREAD

**Issue by R4md4c** [ReactiveCircus/FlowBinding#71]
ComponentActivity has [OnBackPressedDispatcher](https://developer.android.com/reference/androidx/activity/OnBackPressedDispatcher) to handle the back presses from outside an Activity (e.g. Fragment) without tightly coupling the Fragment to the Activity, and it does that through a [OnBackPressedCallback](https://developer.android.com/reference/androidx/activity/OnBackPressedCallback.html).

It would be nice to expose such capability through FlowBinding.

**Comment by ychescale9** [comment]
Added this in a new `flowbinding-activity` artifact ([PR](https://github.com/ReactiveCircus/FlowBinding/pull/74)). Please let me know what you think 😃

**Comment by ychescale9** [comment]
This has been released in `0.9.0`. Should be available on Maven Central soon.
