### ISSUE TITLE
Is there something similar to debounce operator in RxJava to avoid multiple rapid touches?

### ISSUE THREAD

**Issue by anticafe** [ReactiveCircus/FlowBinding#76]

**Comment by ychescale9** [comment]
Yes `Flow` also has a [`debounce` operator](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/debounce.html).

Example:
```kotlin
searchEditText.textChanges()
    .debounce(1000)
    .onEach { text ->
        // process text
    }
    .launchIn(lifecycleScope)
```

**Comment by anticafe** [comment]
Ah it sounds good when such operator is already available. Thanks for your support.
