### ISSUE TITLE
[Discussion] Reduce minSdkVersion?

### ISSUE THREAD

**Issue by JacquesSmuts** [ReactiveCircus/FlowBinding#79]
Is there any chance you can reduce the minSDK to 15?

**Comment by ychescale9** [comment]
Personally I'd like to see the ecosystem moved forward but understand not all codebases are there yet and it's not just a technical decision to make.

Changing `minSdkVersion` to 15 would probably work but would likely introduce more maintenance cost especially on the `flowbinding-android` artifact which binds platform APIs, and testing (need to setup CI and tooling for old Emulator etc).

Let's see whether more people are interested in a lower minSdkVersion and decide whether it's worth doing 😃 

------

**To everyone who cares about `minSdkVersion` for FlowBinding: please give your 👍 or 👎  or leave comment. Thanks!**

**Comment by yrezgui** [comment]
Personally supporting SDK 19 would the lowest API level I would accept. https://developer.android.com/about/dashboards numbers aren't up to date (Android 10 isn't there) and API level less 19 numbers are much lower now.

**Comment by ychescale9** [comment]
@yrezgui Thanks your input. Supporting API level < 21 is roughly the same effort whether it's 14+ or 19+. While the overall percentage of API 15 users seems small, for developers targeting a specific (emerging) market like Africa users this may have a much bigger impact. Here's a [tweet](https://twitter.com/JacquesSmuts/status/1232524760875139072?s=20)  with more context.
